#!/usr/local/bin/python

from datetime import date,datetime,time

today = datetime.today().date()

date_of_birth = raw_input("Birthday (Please enter in the format of dd/mm/yyyy): ")
format_str = '%d/%m/%Y' # The format
birthday = datetime.strptime(date_of_birth, format_str).date()
days_until_birthday = (birthday-today).days
days_alive = (today-birthday).days

print( 'You are ' + str(days_alive) + ' days old')

if days_until_birthday > 0:
        print( 'It\'s ' + str(days_until_birthday) + ' days until your Birthday')
elif days_until_birthday == 0:
        print( 'Happy Birthday!')
else:
        print( 'You\'ll have to wait until next year for another birthday')


print('You pig')
